# Generated by Django 3.1 on 2020-08-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.PositiveIntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('last_update', models.DateField()),
            ],
        ),
    ]
